# Generated by Django 5.0.1 on 2024-02-09 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('userinfo', models.CharField(blank=True, max_length=255, null=True)),
                ('feature', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('CREATE', 'CREATE'), ('DELETE', 'DELETE'), ('MODIF', 'MODIF'), ('ASKMEYA', 'ASKMEYA'), ('NAVIGATE', 'NAVIGATE'), ('CHOOSE', 'CHOOSE'), ('DISCONNECT', 'DISCONNECT')], max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
